name: Continuous Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scala:
    uses: deed-ie/github-workflows/.github/workflows/continuous-integration.yml@main

  swagger:
    uses: deed-ie/github-workflows/.github/workflows/swagger-definition-validation.yml@main
    with:
      SWAGGER_DEFINITION_FILE: api/src/main/resources/swagger/v1.yaml
