name: Continuous Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scala:
    uses: nok-ie/github-workflows/.github/workflows/scala-test.yml@main

  swagger:
    uses: nok-ie/github-workflows/.github/workflows/swagger-definition-validation.yml@main
    with:
      SWAGGER_DEFINITION_FILE: api/src/main/resources/swagger/v1.yaml
